name: tag-release

# only runs on master push AFTER full ci lint/test/build job matrix completes.
on:
  workflow_run:
    workflows:
      - lint-test-build
    branches:
      - master
    types:
      - completed

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # pull all tags also
          fetch-depth: 0
      - name: run tag pipeline.
        uses: pypyr/run-in-tox-action@master
        with:
          pipeline: tox ops/tag